public class Main{
    public static void main(String[] args){
      int x = 0;
      int y = 0;
      
      for(x = "for what".length(); x <= 10; x++){
        System.out.print("l ");
          for(x = "for score four years ago".length(); x == 0 ; x--){ 
            System.out.print("+ ");
            for(x = "for score four years ago".length(); x != -42 ; x--){ 
            System.out.print("NVM you are redeemed ");
            }
            
          }
      }
    String sTrInG = "StRiNg";
            for(y = sTrInG.length()-1; 0 < y; y --){
              System.out.print(sTrInG.substring(y - 1, y));
                               }
             for(y = sTrInG.length(); 0 <= y; y --){
              System.out.print(sTrInG.substring(y - 1, y));
             }
              for(x = 0;x < 1; x++){
                System.out.println("i");
                               }
              x= 0;
              while(x<1){
                System.out.println("i");
                x++;
              }
  
  
  
  }
  }
  
        
  
  